(load "src/package.lisp")
(load "src/core.lisp")
(let* ((args (cdr sb-ext:*posix-argv*))
       (path (or (first args) "src/rules.lisp")))
  (multiple-value-bind (nodes src err) (lintsp::read-file path)
    (declare (ignore src))
    (format t "~&ERR=~A N=~D~%" err (length nodes))
    (let ((prev 0))
      (dolist (n nodes)
        (let ((end (or (lintsp::node-end-line n) (lintsp::node-line n))))
          (when (> (- (lintsp::node-line n) prev) 1)
            (format t "  GAP L~D..L~D before ~A~%" (1+ prev) (1- (lintsp::node-line n))
                    (lintsp::node-head n)))
          (setf prev end))))))
